// libs
import Head from 'next/head'
import {
  AppBar,
  Toolbar,
  Container,
  Typography,
  List,
  Table,
  TableBody,
  TableHead,
  TableRow,
  TableCell,
  Box,
  IconButton,
} from "@mui/material";
import DeleteIcon from '@mui/icons-material/Delete';

export default function Home() {
  const data = [
    {
      "path": "files",
      "name": "files",
      "children": [
        {
          "path": "files/.DS_Store",
          "name": ".DS_Store",
          "mtime": "2022-11-30T17:16:29.447Z",
          "size": 6148
        },
        {
          "path": "files/check.json",
          "name": "check.json",
          "mtime": "2022-11-30T16:40:03.497Z",
          "size": 0
        },
        {
          "path": "files/folder",
          "name": "folder",
          "children": [
            {
              "path": "files/folder/Screenshot 2022-11-28 at 20.44.42.png",
              "name": "Screenshot 2022-11-28 at 20.44.42.png",
              "mtime": "2022-11-30T17:16:29.215Z",
              "size": 274850
            },
            {
              "path": "files/folder/check2.json",
              "name": "check2.json",
              "mtime": "2022-11-30T17:01:05.388Z",
              "size": 0
            },
            {
              "path": "files/folder/folder.json",
              "name": "folder.json",
              "mtime": "2022-11-30T17:16:23.945Z",
              "size": 0
            }
          ],
          "mtime": "2022-11-30T17:16:29.214Z",
          "size": 274850
        }
      ],
      "mtime": "2022-11-30T17:13:14.624Z",
      "size": 280998
    },
    {
      "path": "files",
      "name": "files",
      "children": [
        {
          "path": "files/.DS_Store",
          "name": ".DS_Store",
          "mtime": "2022-11-30T17:16:29.447Z",
          "size": 6148
        },
        {
          "path": "files/check.json",
          "name": "check.json",
          "mtime": "2022-11-30T16:40:03.497Z",
          "size": 0
        },
        {
          "path": "files/folder",
          "name": "folder",
          "children": [
            {
              "path": "files/folder/Screenshot 2022-11-28 at 20.44.42.png",
              "name": "Screenshot 2022-11-28 at 20.44.42.png",
              "mtime": "2022-11-30T17:16:29.215Z",
              "size": 274850
            },
            {
              "path": "files/folder/check2.json",
              "name": "check2.json",
              "mtime": "2022-11-30T17:01:05.388Z",
              "size": 0
            },
            {
              "path": "files/folder/folder.json",
              "name": "folder.json",
              "mtime": "2022-11-30T17:16:23.945Z",
              "size": 0
            }
          ],
          "mtime": "2022-11-30T17:16:29.214Z",
          "size": 274850
        }
      ],
      "mtime": "2022-11-30T17:13:14.624Z",
      "size": 280998
    },
    {
      "path": "files",
      "name": "files",
      "children": [
        {
          "path": "files/.DS_Store",
          "name": ".DS_Store",
          "mtime": "2022-11-30T17:16:29.447Z",
          "size": 6148
        },
        {
          "path": "files/check.json",
          "name": "check.json",
          "mtime": "2022-11-30T16:40:03.497Z",
          "size": 0
        },
        {
          "path": "files/folder",
          "name": "folder",
          "children": [
            {
              "path": "files/folder/Screenshot 2022-11-28 at 20.44.42.png",
              "name": "Screenshot 2022-11-28 at 20.44.42.png",
              "mtime": "2022-11-30T17:16:29.215Z",
              "size": 274850
            },
            {
              "path": "files/folder/check2.json",
              "name": "check2.json",
              "mtime": "2022-11-30T17:01:05.388Z",
              "size": 0
            },
            {
              "path": "files/folder/folder.json",
              "name": "folder.json",
              "mtime": "2022-11-30T17:16:23.945Z",
              "size": 0
            }
          ],
          "mtime": "2022-11-30T17:16:29.214Z",
          "size": 274850
        }
      ],
      "mtime": "2022-11-30T17:13:14.624Z",
      "size": 280998
    }
  ]

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AppBar position="static">
          <Toolbar>
            <Container>
              <Typography variant="h6">
                File & Directory Browsing Single Page App
              </Typography>
            </Container>
          </Toolbar>
        </AppBar>
        <Box py={4}>
          <Container>
            <List>
              <Table aria-label="simple table">
                <TableHead>
                  <TableRow>
                    <TableCell>Name</TableCell>
                    <TableCell>Size</TableCell>
                    <TableCell align="center">Action</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {data.map((row, index) => (
                    <TableRow key={index}>
                      <TableCell>{row.name}</TableCell>
                      <TableCell>{row.size}</TableCell>
                      <TableCell align="center">
                        <IconButton aria-label="delete" size="large">
                          <DeleteIcon fontSize="inherit" />
                        </IconButton>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </List>
          </Container>
        </Box>
      </main>
    </>
  )
}
